#!/usr/bin/env bash

joblimit=16
script=$0
domain=$1
db=$2
useragent=$3

ENABLE_SYNOPSES=1
if [ "$domain" = pasteboard ]; then
  ENABLE_SYNOPSES=0
fi

if [ -n "$VISUAL" ]; then
  view=$VISUAL
elif [ -n "$EDITOR" ]; then
  view=$EDITOR
elif [ -n "$PAGER" ]; then
  view=$PAGER
else
  view=more
fi

APPEND_DOMAIN_TO_DATA=0


DARKGREEN=$'\e[00;32m'
GREEN=$'\e[01;32m'
TEAL=$'\e[00;36m'
DARKGREY=$'\e[01;30m'
CYAN=$'\e[01;36m'
LIGHTGREY=$'\e[00;37m'
RED=$'\e[00;31m'
PINK=$'\e[01;31m'
BLACK=$'\e[00;30m'
BLUE=$'\e[01;34m'
DARKBLUE=$'\e[00;34m'
WHITE=$'\e[01;37m'
RESET=$'\e[0m'
YELLOW=$'\e[01;33m'
MAGENTA=$'\e[01;35m'
PURPLE=$'\e[00;35m'

MUTEX=0
LAST_SYNOPSIS=$(mktemp)

if which dos2unix &> /dev/null ; then
  DOS2UNIXPIPE=dos2unix 
else
  DOS2UNIXPIPE=cat
fi

UP=$'\033[1A'
DOWN=$'\033[1B'
BOTTOM=$'\033[256B'
SAVE=$'\033[s'
DELEOL=$'\033[0J'
RESTORE=$'\033[u'
BANNER=${GREEN}'
 __ \                             |              __ \ _)                 
 |   | |   | __ `__ \  __ \   __| __|  _ \  __|  |   | |\ \   / _ \  __| 
 |   | |   | |   |   | |   |\__ \ |    __/ |     |   | | \ \ /  __/ |    
____/ \__,_|_|  _|  _| .__/ ____/\__|\___|_|    ____/ _|  \_/ \___|_|    
                      _|  '${DARKGREEN}'                                               
                      __________________
                      \                 \
                        \                 \
                          \                 \
                            \                 \
           /-------------------------------------
         //---------------//                  / |
       //               //                  / __|
     //               //                  / /  ||
   //               //                  / /    ||
 //_______________//   '${YELLOW}'o o'${DARKGREEN}'            / /      ||      ___/-\___
------------------------------------/   ------- |     |---------|
| '${GREEN}'BRUTE FORCE '${DARKGREEN}'|        | '${GREEN}'FIND WEIRD'${DARKGREEN}' |           |      | | | | |
|  '${GREEN}'PASTEBINS'${DARKGREEN}'  |        |    '${GREEN}'SHIT'${DARKGREEN}'    |           |      | | | | |
|--------------        -------------|           |      | | | | |
|                                   |           |      | | | | |
-------------------------------------------------      |_______|

'
function greet ()
{

  default_bin=ghostbin.com
  default_ua="Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
  default_db="visited.db"
  [ -n "$domain" ] || bin="$default_bin"
  loot=$domain-loot
  [ -n "$useragent" ] || useragent="$default_ua"
  [ -d "$loot" ] || mkdir $loot
  [ -n "$db" ] || db="$default_db"

  echo "${DARKGREEN}"
  echo "${BANNER}"
  echo "${GREEN}Usage: $script [pastebin name] [sqlite3 db] [user agent]"
  echo "${DARKGREEN}Using: domain:     $domain"
  echo             "       database:   $db"
  echo             "       user-agent: \"$useragent\""
  echo -e "\n${GREEN}HIT <ENTER> TO CONTINUE...${RESET}"
  read
  echo -e "\n"
}


function bottom_scr ()
{
  echo -en
}

function fadebar ()
{
  i=0
  num=$1
  if (( $num < 0 )); then
    num=$(( $num * -1 ))
    pipe=tac
  else
    pipe=cat
  fi
  for colour in ${DARKGREY} ${LIGHTGREY} ${TEAL} ${CYAN} ${WHITE}; do
    for i in `seq 1 $num`; do
      echo -e "${colour}=${colour}"
    done
  done | $pipe | tr -d '\n'
  echo -en "${RESET}"
}

function freemem ()
{
  free -m | awk '{print $4}' | head -n 2 | tail -n 1
}

function freemem_echo ()
{
  fm=$(freemem)
  if (( $fm < 128 )); then
    echo "${PINK}[${fm}M free]${RESET}"
  else
    echo "${DARKGREY}[${fm}M free]${RESET}"
  fi
}

function lootcount_echo ()
{
  echo "${DARKGREY}[$(ls $loot | wc -l | awk '{print $1}') looted]${RESET}"
}

function httpcode_echo ()
{
  code=$1
  color=$DARKGREY
  case "$code" in 
    1*)
      colour=$WHITE
      ;;
    200)
      colour=$CYAN
      ;;
    2*)
      colour=$TEAL
      ;; 
    3*)
      colour=$BLUE
      ;;
    403)
      colour=$PINK
      ;;
    404)
      colour=$DARKGREY # most common, and to be expected
      ;;
    5*)
      colour=$YELLOW
      ;;
    *)
      colour=$GREEN # ???
      ;;
  esac
  echo "${DARKGREY}[${colour}${code}${DARKGREY}]${RESET}"
}

function timestamp_echo ()
{
  echo "${DARKGREY}[$(date +"%F %T")]${RESET}"
}

function mutex_acquire ()
{
  while (( $MUTEX )); do
    sleep 0.1
  done
  MUTEX=1
}

function mutex_release ()
{
  MUTEX=0
}


function mecho ()
{
  while (( $MUTEX )); do
    sleep 0.1
  done
  MUTEX=1
  echo $@
  MUTEX=0
}

function mcat ()
{
  while (( $MUTEX )); do
    sleep 0.1
  done
  MUTEX=1
  cat $@
  MUTEX=0
}

function sqlite_execute(){
    while :; do
        result=$(sqlite3 $1 "${2}" 2>&1) #| tee /dev/stderr)
        if [ "${result}" = "Error: database is locked" ]; then
            sleep 0.01
            continue
        else
            break
        fi
    done
    echo -n "${result}"
}

function makeurl(){
    case "$domain" in
        termbin.com)
            n=4
            charset=a-z0-9
            prefix="http://termbin.com"
            key=$(cat /dev/urandom | tr -dc $charset | head -c $n)
            echo "${prefix}/${key}"
            ;;
        pastebin.com)
            n=8
            charset=a-z0-9
            prefix="https://pastebin.com/raw"
            key=$(cat /dev/urandom  | tr -dc $charset | head -c $n)
            echo "${prefix}/${key}"
            ;;
        ghostbin.com)
            n=5
            charset=a-z0-9
            prefix="https://ghostbin.com/paste"
            key=$(cat /dev/urandom | tr -dc $charset | head -c $n)
            suffix="raw" # or download
            echo "${prefix}/${key}/${suffix}"
            ;;
        paste.ee)
            n=5
            charset=a-z0-9
            prefix="https://paste.ee/p"
            key=$(cat /dev/urandom  | tr -dc $charset | head -c $n)
            suffix="0"
            echo "${prefix}/${key}"
            ;;
        p.ip.fi)
            n=4
            charset=a-z0-9
            prefix="http://p.ip.fi"
            key=$(cat /dev/urandom | tr -dc $charset | head -c $n)
            echo "${prefix}/${key}"
            ;;
        pasteboard.co)
            n=4
            charset=A-Za-z0-9
            prefix="https://pasteboard.co/images/"
            prekey=HcF # is this invariant?
            key=$(cat /dev/urandom | tr -dc $charset | head -c $n)
            suffix=/download
            echo "${prefix}/${prekey}${key}/${suffix}"
            ;;
    esac
}

function synopsis () {
  file="$1"
  url="$2"
  cols=$(tput cols)
  rows=$(tput lines)
  showrows=$(( (rows - 10) / 2 ))
  bytes=$(wc -c $file | awk '{print $1}')

  echo $file > $LAST_SYNOPSIS
  clear
  (
    echo "${WHITE},--- BEGIN SYNOPSIS ---"
    echo -n ${GREEN} && cat $file \
      | $DOS2UNIXPIPE \
      | grep -vP "^\s*$" $file \
      | head -n $showrows \
      | sed "s/^/${WHITE}|${GREEN} /g"
    rem=$(( $(wc -l $file | awk '{print $1}') - $showrows ))
    if (( $rem > 0 )); then
      (( $rem > $showrows )) && rem=$showrows
      echo -n ${DARKGREEN} && (cat $file && echo) \
        | $DOS2UNIXPIPE \
        | grep -vP "^\s*$" $file \
        | tail -n $rem \
        | sed "s/^/${WHITE}|${DARKGREEN} /g"
    fi
    echo -e "${WHITE}|${CYAN} $url"
    echo -e "${WHITE}|${CYAN} $file${RESET}"
    echo -e "${WHITE}|${CYAN} $bytes bytes: SIGINT to view${RESET}"
    echo -e "${WHITE}\`--- END SYNOPSIS -----${RESET}\n\n\n"
    ) | sed -e "/.\{$cols\}/ s/^\(.\{$(( cols - 20 ))\}\).*\(.\{15\}\)$/\1[...]\2/" \
      | cat
}

function pii(){
    file=$1
    hits=0
    #reg_cc="(?:4[0-9]{12}(?:[0-9]{3})?|[25][1-7][0-9]{14}|6(?:011|5[0-9][0-9])[0-9]{12}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|(?:2131|1800|35\d{3})\d{11})"
    cat $file \
      | grep -P "([0-9]{1,3}\.){3}[0-9]{1,3}" \
      | grep -vP "(127(\.[0-9]{1,3}){3}|0\.0\.0\.0)" \
      >> ${file}.pii \
      && hits=$(( hits + 1 ))
    
    # now look for cryptocurrency keys
    cat $file \
      | grep -wP '[5KL][1-9A-HJ-NP-Za-km-z]{50,51}' \
      >> ${file}.pii \
      && hits=$(( hits + 1 ))

    # email
    cat $file \
      | grep -P "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}" \
      >> ${file}.pii \
      && hits=$(( hits + 1 ))

    # private keys and credentials
    cat $file \
      | grep -P "(PRIVATE KEY|password|credential|0day)" \
      >> ${file}.pii \
      && hits=$(( hits + 1 ))
    
    echo $hits
}

function hitrate () {
  sqlite_execute $db "SELECT (count(md5)*1.0)/count(*) 
                      FROM urls 
                      WHERE url LIKE '%$domain%';"
}

function hitrate_echo () {
  hr=$(hitrate)
  echo "${DARKGREY}[hit $(printf "%2.3f%%" $(bc <<< "100 * $hr"))]${RESET}"
}

function action(){
    while :; do
      url=$(makeurl)
      db_url=$(sqlite_execute $db "SELECT url FROM urls WHERE url = '${url}'")
      if [ "${url}" = "${db_url}" ]; then
          fademsg "[already vistited $url]"
      else
          break
      fi
    done
    tmp=$(mktemp)
    response=$(curl -A "${useragent}"  \
               --write-out %{http_code} \
               --silent \
               --output $tmp "${url}")
    mutex_acquire
    echo -e "${BOTTOM}${UP}${UP}\r${RESET}$(timestamp_echo)$(freemem_echo)$(lootcount_echo)$(httpcode_echo $response)$(hitrate_echo)\n$(fadebar 2)${WHITE}  $url  $(fadebar -2)"
    if [ "$response" = "200" ]; then
      md5=$(md5sum $tmp | cut -d ' ' -f 1)
      file=${loot}/${md5}
      # Check to see if the file is new to us
      if ! [ -f "$file" ]; then
        data_pii=0 #data_pii=$(pii $tmp)
        sqlite_execute $db "INSERT INTO urls(url, response, pii, md5) 
                            VALUES('${url}', 
                                   '${response}', 
                                   ${data_pii}, 
                                   '${md5}');"
        mv $tmp $file
        #rm ${tmp}.pii
        (( $ENABLE_SYNOPSES )) && synopsis $file $url
      else
        fademsg "[data $md5 from $url is redundant]" &
      fi
    else # if response is not 200
      sqlite_execute $db "INSERT INTO urls(url, response, pii) VALUES('${url}', '${response}', 0);"
      rm -f $tmp
    fi
    mutex_release
}

function fademsg () {
  msg="$*"
  start=$(echo -en "\r${SAVE}")
  for colour in ${WHITE} ${CYAN} ${TEAL} ${LIGHTGREY} ${DARKGREY}; do
    echo -en "${RESTORE}${colour}${msg}${RESET}${DELEOL}${RESTORE}"
    sleep 0.05
  done
}

function throttle(){
  joblimit=$1
  joblist=($(jobs -p))
  while (( ${#joblist[*]} >= $joblimit )); do
    sleep 0.5
    joblist=($(jobs -p))
  done
}

function cleanup () {
  joblist=($(jobs -p))
  jn=${#joblist[*]} 
  echo "${YELLOW}Waiting for $jn jobs to finish...${RESET}"
  wait
  echo "${YELLOW}Goodbye!${RESET}"
  exit
}

function look_closer () {
  S=$(cat $LAST_SYNOPSIS)
  if [ -z "$S" ]; then
    cleanup
  fi
  trap - INT
#  trap cleanup INT
  mecho -e "\n${CYAN}Taking a closer look at $S...\n${PINK}HIT CTRL-C AGAIN TO EXIT...${RESET}"
  wait
  sleep 1
  $view $S
  sleep 1
  trap - INT
  trap look_closer INT
}
trap look_closer INT

#######################################
# Main 
######################################
greet


if [ ! -f $db ]; then
    echo "${YELLOW}$db not found; creating...${RESET}"
    touch $db
    sqlite_execute $db "create table urls(id integer primary key autoincrement, url varchar(512) unique,  response integer, pii integer, md5 varchar(32), sqltime timestamp default current_timestamp not null);"
    echo -e "\n"
fi

if [ "${joblimit}" = "1" ]; then
    while :; do
        action
    done
else
    while :; do
        action &
        throttle $joblimit
    done
fi
